name: Upload dotnet package

on:
  push:
    branches: [ main ]
  release:
    types: [created]

env:
  GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }} 
  GITHUB_API_KEY: ${{ github.token }}            

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '5.0.x' ]
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet-version }} # SDK Version to use.
          source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - run: dotnet build --configuration Release ./src/Modulos/Modulos.csproj
      - name: Pack
        run: dotnet pack ./src/Modulos/Modulos.csproj --output nuget-packages --configuration Release --include-symbols -p:SymbolPackageFormat=snupkg

      - name: NuGet push on GitHub
        run: dotnet nuget push "**/*.nupkg" --source https://nuget.pkg.github.com/${{ env.GITHUB_REPOSITORY_OWNER }}/index.json --api-key ${{ env.GITHUB_API_KEY }} --skip-duplicate

      - name: Upload NuGet package
        uses: actions/upload-artifact@v2
        with:
          name: Modulos
          path: "**/*.nupkg"